spring.application.name=booklovers
spring.datasource.url=jdbc:postgresql://dpg-d8bl7lcua31s739akn50-a.ohio-postgres.render.com/bookclub_4iyb
spring.datasource.username=bookclub_4iyb_user
spring.datasource.password=4Qu9oHC7IvldpU6MgMYOvrVtOumLBTXt
spring.datasource.driver-class-name=org.postgresql.Driver
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

 
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

 
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

jwt.secret=orgpovepojgpvjeijdfjnvkerjfndjnioerkfdvijefdsgvisjdnvklnklxmvpoejdfvdswadfsrdygdrtfhgsnetuhstrgdbnsezdsnhfshedbxxsrjnsggeash
jwt.expiration=86400000